# Generated by Django 3.2.8 on 2021-10-30 16:30

from django.db import migrations, models
import django.db.models.deletion
import instructor.models.assignments


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(choices=[('POSTGRES', 'postgres'), ('MYSQL', 'mysql'), ('MSSQL', 'mssql')], default='POSTGRES', max_length=100)),
                ('initial_code', models.FileField(blank=True, null=True, upload_to=instructor.models.assignments.AssignmentEnvironment.get_file_path)),
                ('assignment', models.ForeignKey(blank=True, on_delete=models.SET(''), to='instructor.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField()),
                ('item_type', models.CharField(choices=[('QUERY', 'Query'), ('SCHEMA', 'Schema')], default='QUERY', max_length=25)),
                ('item_solution', models.FileField(blank=True, null=True, upload_to=instructor.models.assignments.AssignmentItem.get_file_path)),
                ('assignment', models.ForeignKey(blank=True, on_delete=models.SET(''), to='instructor.assignment')),
                ('assignmentenvironment', models.ForeignKey(blank=True, on_delete=models.SET(''), to='instructor.assignmentenvironment')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_name', models.CharField(default='Default', max_length=100)),
                ('initial_code', models.FileField(blank=True, null=True, upload_to=instructor.models.assignments.EnvironmentInstance.get_file_path)),
                ('item', models.ForeignKey(blank=True, on_delete=models.SET(''), to='instructor.assignmentitem')),
            ],
        ),
        migrations.CreateModel(
            name='GradingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_status', models.CharField(choices=[('READY', 'Ready'), ('INITIALIZING', 'Initializing'), ('GRADING', 'Grading'), ('FINISHED', 'Finished'), ('ERROR', 'Error')], default='Ready', max_length=20)),
                ('process_start_time', models.DateTimeField(auto_now_add=True)),
                ('process_end_time', models.DateTimeField(null=True)),
                ('process_error', models.TextField(null=True)),
                ('process_log', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('student_custom_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('is_graded', models.BooleanField(default=False)),
                ('grade', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=models.SET(''), to='instructor.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubmissionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('submission_file', models.FilePathField(match='*.sql', path='/workspaces/sqlgrader/sqlgrader/media/submissions/')),
                ('assignment_item', models.ForeignKey(on_delete=models.SET(''), to='instructor.assignmentitem')),
                ('student_submission', models.ForeignKey(on_delete=models.SET(''), to='instructor.studentsubmission')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='student_group',
            field=models.ForeignKey(blank=True, on_delete=models.SET(''), to='instructor.studentgroup'),
        ),
        migrations.CreateModel(
            name='GradingContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=100)),
                ('container_name', models.CharField(max_length=100)),
                ('container_port', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('grading_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.gradingprocess')),
            ],
        ),
        migrations.CreateModel(
            name='GradingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructor.assignmentitem')),
                ('grading_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.gradingprocess')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentInstanceDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_table_name', models.CharField(max_length=100)),
                ('dataset_file', models.FileField(blank=True, null=True, upload_to=instructor.models.assignments.EnvironmentInstanceDataset.get_file_path)),
                ('environmentinstance', models.ForeignKey(blank=True, on_delete=models.SET(''), to='instructor.environmentinstance')),
            ],
        ),
    ]
