# Generated by Django 3.2.8 on 2021-10-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
