# Generated by Django 3.2.8 on 2021-10-31 03:27

from django.db import migrations, models
import instructor.models.students


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_assignmentitem_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='assignment',
            field=models.ForeignKey(default='', on_delete=models.SET(''), to='instructor.assignment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentsubmissionitem',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to=instructor.models.students.StudentSubmissionItem.get_file_path),
        ),
    ]
