# Generated by Django 3.2.8 on 2021-10-31 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_auto_20211031_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingprocess',
            name='assignment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='instructor.assignment'),
            preserve_default=False,
        ),
    ]
