# Generated by Django 3.2.8 on 2021-10-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_gradingprocess_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingcontainer',
            name='db_type',
            field=models.CharField(choices=[('POSTGRES', 'postgres'), ('MYSQL', 'mysql'), ('MSSQL', 'mssql')], default='POSTGRES', max_length=100),
        ),
    ]
