POST http://localhost:5000/grading/7 HTTP/1.1
Content-Type: application/json
apikey: 435dcd3b2e64164942c7213d1ac53c069e86c228

[{"id": 12, "assignment_item": {"id": 1, "assignmentenvironment": {"db_type": "POSTGRES", "initial_code": "/media/assignmentenv_3/sample-table.sql"}, "item_number": 1, "item_type": "QUERY", "item_solution": "/media/assignmentitem_1/sample-query_CWOZKc4.sql", "item_name": "test query", "assignment": 3}, "grading_process": 7}]



###
POST http://localhost:5000/datagen/5 HTTP/1.1
Content-Type: application/json
apikey: 435dcd3b2e64164942c7213d1ac53c069e86c228

{"db_type": "POSTGRES", "assignment_item_id": "1", "env_code": "assignmentenv_3/sample-table.sql", "initial_code": "", "row_count": "100"}


###
POST http://localhost:80/instructor/api_updateenvironmentinstance HTTP/1.1
Content-Type: application/json
Authorization: Token 435dcd3b2e64164942c7213d1ac53c069e86c228

{"environment_instance_id": 8, "datagen_status": "completed", "has_datagen": "True"}

